### PR TITLE
Prefer PRs to comments

### PR DESCRIPTION
**Pull request by bitwiseman**
This is an example of the idea I'd like to try.  As noted in #12, and in the comments below I'd like to recommend (or at least describe) in JEP-1 how changes to a JEP can be suggested, refined, and merged to a JEP Draft. 

The intent of this idea was motivated by the limitations of the Github PR UI, but I'm wondering if it might have other benefits.  
* Quicker turn-around - If people spot more than a few typos, submitting a PR to fix all of them is about the same amount of effort for the reviewer as making the comments and is much easier for the sponsor or other contributors. 
* Focus on outcomes - Comments seem guide people toward asking if something can be done rather than doing it.  As with typos, talking about doing something often takes more effort than writing something concrete, submitting it as a PR, and doing a couple iterations on that PR. 
* Alternate views easy to add to "Reasoning" - I ended up adding several topic to the Reasoning section based on comments.  If these comments had been in their own PR, it would have been easier for those who proposed the ideas to move them to the Reasoning section for merging, rather than bottlenecking at one contributor making changes.

This is obviously a work in progress.  I'd like feedback before trying to hammer out details.

@jenkinsci/jep-editors @daniel-beck

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
I would like to exercise my JEP Editor rights and to add @daniel-beck to JEP Editors. I am pretty sure we need the current Jenkins security officer in the Editors list. It also saves time when filling in the CC list :)

**Comment by bitwiseman** [comment]
@oleg-nenashev I have no objection, but please raise that on the dev mailing list.  It is possible he doesn't want the added work. 😄

**Comment by rtyler** [comment]
@bitwiseman I'm also in favor of this, and that was part of the reasoning (however poorly I stated it) for the `jep-X` branches.

Honestly if people spent half the time proposing changes rather than just commenting on *all* Jenkins PRs..... :smile:

**Comment by bitwiseman** [comment]
@jenkinsci/jep-editors @daniel-beck 

This workflow is slightly harder for the reviewer but not significantly.  I'm trying it with @StackScribe
in  https://github.com/cloudbees/training-pipeline-intro/pull/6 and it seems pretty good. 
The github UI let me create a PR against that PR (https://github.com/StackScribe/training-pipeline-intro/pull/1) and @StackScribe was able to agree and merge the change quickly and easily, and then merge the original PR.  It was significantly faster than reviewing PR6,  commenting the PR6, StackScribe making and pushing changes, reviewing the PR6 again, approving the PR6, and finally StackScribe merging PR6.

Github has a button for editing a file in a PR, the pencil button in the upper right corner: 

screen shot 2017-09-29 at 2 20 54 pm

Made the edits I thought were needed, and committed them to separate branch for PR:

screen shot 2017-09-29 at 2 21 51 pm

Github then took me to the pull request creation page and I created a PR into the branch of the original PR.  Easy. 

The only notable hitch I see is that the Github UI will only edit on file at a time this way and it doesn't display the diff in the edit window. 

Having thought about this a bit, I can see this (like the style guidelines) is outside the scope of this JEP, and will be closing this PR without merging.  However, I'd still like people's early feedback on what will be a JEP short after JEP-1 is accepted.

**Comment by daniel-beck** [comment]
Also, for those with repo write access, no way to do it in a branch on a fork from that dialog. If we're okay with (potentially many, not cleaned up) branches in origin, that's no problem.

**Comment by bitwiseman** [comment]
One existing tool related to this: 
https://github.com/splitbrain/git-pull-request

**Pull request closed without merging**
