### PR TITLE
JEP submission for Modular Components

### PR DESCRIPTION
**Pull request by sophistifunk**
Hi All,

I'm (attempting to) submit the JEP for Modular Components covering the details of reusable "Widgets" extracted from Blue Ocean. Please bear with me and let me know if I'm going about the submission process the wrong way as it's the first JEP I've been asked to do :)

From the abstract:

> This document describes a set of practices to allow creation and embedding of Modular UX Widgets: Compound React components that are more task-specific and self-contained than the simpler, building-block kind of components found in a common UI Component library package (such as Button, Table, DropDown, etc).

### CODE REVIEW

**Comment by bitwiseman** [comment]
@sophistifunk 
This is a good start, not quite ready for draft. 

Please put the sections in the order they are shown in the template.  They are in that order for a reason (yes, motivation matters to you now, but in the future the motivation will be quite a bit less interesting than the specification). 

Generally we'd start a new JEP with a sanity check discussion on the jenkins-dev ML.  If you want to submit this before starting that discussion, it is still valid, but you should be prepared for plenty of feedback either way.  Once you've made the changes to the section order, just say whether you want to go to draft and then email the ML or ML first.

**Comment by sophistifunk** [comment]
I moved the sections around. Not sure what you mean by "draft and then email the ML or ML first", as I'm new to the whole JEP business.

**Comment by bitwiseman** [comment]
Okay, well, please take a minute to at least read the [overview section of JEP-1 ](https://github.com/jenkinsci/jep/tree/master/jep/1#overview) .   I was asking if you wanted to skip step 1 in that overview since what you're proposing was already raise by @kohsuke last week. 

Now that you have the sections in the right order and have sufficient information for discussion, I'm going to call this approve this as draft and we can go from there.

**Comment by bitwiseman** [comment]
@sophistifunk  Could you grant jep-editors (or at least me) access your fork as a contributor.  It is usually done automatically when you create the for, but for some reason yours doesn't have it.  I need that to make the updates to this PR needed to approve this as draft.

**Comment by sophistifunk** [comment]
Done. GH told me there's no such user as jep-editors, but it allowed me to add you specifically.

**Comment by bitwiseman** [comment]
@sophistifunk consider forking from jenkinsci/jep instead of imeredith/jep.

**Comment by sophistifunk** [comment]
@bitwiseman Thanks for your help 👍

**Pull request merged**
