### PR TITLE
Mark JEP-222 as Final

### PR DESCRIPTION
**Pull request by jglick**
In an LTS; no further work planned for now.

### CODE REVIEW

**Review by oleg-nenashev — DISMISSED** [review]
Needs APIs to be promoted to the Final state

**Comment by oleg-nenashev** [comment]
Also, we cannot easily move to Final without having a BDFL delegate IMHO. Let's take it to the governance meeting

**Comment by jglick** [comment]
> Needs APIs to be promoted to the Final state

Really? The APIs are there in case a legitimate usage from a plugin is found. To date there is none, though there is a _potential_ usage in a proprietary plugin I know of.

**Comment by jglick** [comment]
> without having a BDFL delegate

Oh is that still a thing when we have no active BDFL? In that case maybe never mind, I do not _really_ care what the JEP status is.

**Comment by jglick** [comment]
> there is a _potential_ usage in a proprietary plugin I know of

@Vlatombe has implemented that successfully, for the record.

**Comment by jglick** [comment]
What about Accepted state?

**Review by timja — APPROVED** [review]
JEP 1 states:

>  **<<final, Final Status>>** - When the implementation is complete
  and all changes have been published
  or otherwise incorporated into the appropriate code repositories,
  the JEP status is changed to "<<final, Final>>"
  (or in some cases "<<active, Active>>").
  The JEP is done.

This meets that criteria, will hold off a bit for any more feedback from Oleg before merging, (ping me here if there's no response and I forget)

**Pull request merged**
