### PR TITLE
[JENKINS-38381] Draft JEP

### PR DESCRIPTION
**Pull request by jglick**
Submitted for approval as draft JEP by @jenkinsci/jep-editors. CC @oleg-nenashev @carlossg @svanoort @abayer @rsandell @dwnusbaum

### CODE REVIEW

**Comment by svanoort** [comment]
I do not understand why this would be a JEP?  The parts that seem JEP-appropriate are well-covered by JEP-207 and https://github.com/jenkinsci/jep/pull/151 and the parts that are not there are simply implementation details.

Implementations are supposed to be handled via normal code review process.  Or are we assuming that every single code change we do should have a JEP associated with it?

**Comment by svanoort** [comment]
Actually... I'll go a step further than that: explaining implementation details *should* go into the repo with the code change -- either as docs files or code comments.  And I'd really like to see those code changes get finished.

**Comment by jglick** [comment]
JEP-207 + #151 covers general changes including for freestyle; I expect these to be reconciled.

The specific topics in Pipeline covered here go far beyond implementation details or simple bug fixes and merit the structure of a JEP. This was confirmed recently in the JOM by @bitwiseman and others.

**Comment by oleg-nenashev** [comment]
+1. I believe it should be a JEP. It is a major API enhancenent for
Pipeline users

**Comment by oleg-nenashev** [comment]
#151 actually depends on this draft  in the current design (Pipeline logging bridge methods)

**Comment by jglick** [comment]
And of course individual PRs do add Javadoc for newly introduced API members, which is the authoritative source of information about fine details like that. I make no attempt to duplicate all of that content here, only highlight the more subtle or critical aspects. The JEP is here to describe the higher-level _purpose_ of the entire assembly, within the context of one or more reference implementations, and should be the permanent record of that overall design.

**Pull request merged**
