### PR TITLE
Simplified branch handling

### PR DESCRIPTION
**Pull request by jglick**
As compared to #25, this is what I actually want, not what I tried to infer someone else wanted.

### CODE REVIEW

**Comment by rtyler** [comment]
My original motivation for not landing things left and right in the `master` branch is that the `master` branch in the current JEP-1 indicates more or less what's been approved without requiring much searching around.

Landing documents in various stages of the workflow doesn't bother me, but this to me is strictly an editor workflow question and doesn't really tangibly affect most people.

Therefore I would like a judgement call from the other @jenkinsci/jep-editors

**Comment by daniel-beck** [comment]
> doesn't really tangibly affect most people

What's the expected workflow of an active project contributor wanting to review and provide feedback to in-progress JEPs? Would every such JEP always have a corresponding PR? Going through branches seems cumbersome.

**Comment by rtyler** [comment]
> What's the expected workflow of an active project contributor wanting to review and provide feedback to in-progress JEPs? Would every such JEP always have a corresponding PR? Going through branches seems cumbersome.

Based on how we have handled JEP-1, there would be an open PR to master branch for each branch in my mind which provides a central review point

**Comment by bitwiseman** [comment]
@rtyler - But as we saw with JEP-1, that means that PR gets really long and cumbersome.  It also encourages people to comment on the PR instead of submitting PR's and discussing on the dev-list. 

In this "master branch", the central point of review for all Draft JEPs is the `HEAD` of `master` and then consider any open PRs.

**Comment by jglick** [comment]
> script(s) could automatically generate an overview file (or update the readme) indicating the current status of all JEPs

Yes! To me it just seems much simpler to be able to tell people: look in this repo (GitHub will select `tree/master/` by default) and you will see all JEPs, listed by number. As soon as a JEP is accepted as a draft and gets a number it appears here and never goes away. If we want to develop some tool to produce a summary by status [like the JCP does](https://jcp.org/en/jsr/stage), great.

(At some point we may wish to add a metadata field indicating a target release date, where applicable, which would allow us to produce something like an actual roadmap for Jenkins as a whole for the first time. Currently I think only [Blue Ocean has any equivalent](https://jenkins.io/projects/blueocean/roadmap/).)

**Comment by omehegan** [comment]
I reviewed this at @rtyler's request and I think it sounds reasonable. I don't have a strong opinion.

**Comment by bitwiseman** [comment]
Editors seem to be agreed.  `master` is good.

**Pull request merged**
