### PR TITLE
Accept JEP-201

### PR DESCRIPTION
**Pull request by bitwiseman**
@oleg-nenashev @jglick @kohsuke 
https://github.com/jenkinsci/jep/pull/108 provides context for the changes made to this JEP. 
There are at least to follow up JEPs in the pipe: tooling and schema.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Needs BDFL Delegate approval before merging. It's not clear to me whether there is such approval in #108

**Comment by bitwiseman** [comment]
@oleg-nenashev discussing with KK now.

**Comment by daniel-beck** [comment]
Didn't we have feedback from @jglick critical about the "natural" structure from XML hierarchy? If so, are we no longer including substantial feedback in some "answered but rejected" form in JEPs?

**Comment by daniel-beck** [comment]
(Please note I'm not a JEP editor, so my review means nothing. Commit access via org ownership.)

FWIW the section 'Intuitive schema' is included here but no concern about the status of Blue Ocean is mentioned, but if @bitwiseman things it can be deferred, I'm not opposed.

**Comment by bitwiseman** [comment]
I discussed this with @kohsuke and he verbally said he agreed with this being accepted.  He's traveling  now. I'll go ahead and merge this change.

**Pull request merged**
