### PR TITLE
BlueOcean extensibility

### PR DESCRIPTION
**Pull request by imeredith**

### CODE REVIEW

**Comment by daniel-beck** [comment]
Is there a discussion for this?

**Comment by imeredith** [comment]
@daniel-beck Sorry I just opened this last night and didnt leave any comments. The BlueOcean team have discussed this, and these JEPs are a result. I opened this PR to get feedback on its layout, as well as to use as reference in an email to the mailing list //cc @rtyler

**Comment by bitwiseman** [comment]
@imeredith  Suggest at least splitting each sentence onto separate lines for easier review feedback/diffs.

**Comment by imeredith** [comment]
@bitwiseman Yes this is an overview. I will make changes you suggested.

**Pull request merged**
