### PR TITLE
New JEP: External Build Logging support in the Jenkins core

### PR DESCRIPTION
**Pull request by oleg-nenashev**
https://issues.jenkins-ci.org/browse/JENKINS-52691

@carlossg @jglick @jenkinsci/jep-editors

### CODE REVIEW

**Comment by bitwiseman** [comment]
@oleg-nenashev  Suggestions for BDFL Delegate?

**Comment by oleg-nenashev** [comment]
@carlossg or @jglick, but generally I expect the most of the discussion to happen at the Cloud Native SIG

**Comment by jglick** [comment]
I expect to review this.

**Comment by bitwiseman** [comment]
@jglick @oleg-nenashev  Do you have a number preference for this JEP?

**Comment by oleg-nenashev** [comment]
@bitwiseman Just `JEP-207`?

**Comment by jglick** [comment]
@bitwiseman unfortunately now it is going to be much harder to comment on individual lines of the JEP. Do I continue to comment on the merged PR or what?

**Comment by oleg-nenashev** [comment]
Jesse, per-line comments here work for me. Generally reviewability is a
fundamental flaw of the current process, we cannot do much about that

**Comment by oleg-nenashev** [comment]
Some feedback is addressed in https://github.com/jenkinsci/jep/pull/149

**Pull request merged**
