### PR TITLE
Maybe move `jenkins.slaves.restarter`

### PR DESCRIPTION
**Pull request by jglick**
https://github.com/jenkinsci/remoting-opentelemetry-plugin/issues/65#issuecomment-883754559 for context. I need to think about this a bit more.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
CC @Aki-7 for the reference

**Review by oleg-nenashev — COMMENTED** [review]
I am not sure about it on my own. The Agent installer components were designed for installing the payload on the agent side, not for other common operations like restarts. While we could change the design of the components, it does not seem to fit the existing architecture

**Comment by timja** [comment]
FTR the restarters are broken on Mac M1 ARM

Agent throws a class not found exception and controller exits without restarting

**Comment by jglick** [comment]
> The Agent installer components were designed for installing the payload on the agent side, not for other common operations like restarts.

Right; my reasoning was that attempting to have an agent restart in place (rather than just exit and let a service launch a new copy) falls into the same category of stuff that only makes sense for agents launched interactively via JWS that can be omitted from modern Jenkins installations.

**Comment by jglick** [comment]
I would need to spend more time thinking through implications and testing before actually doing it. Approving an edit to the JEP does not imply approving the _action_; the whole thing remains in draft anyway (despite SSHD being done).

**Review by timja — APPROVED** [review]

**Pull request merged**
