### PR TITLE
JEP-13: Change JIRA component for Infra to account

### PR DESCRIPTION
**Pull request by justinharringa**
It looks like there isn't a formalized component but `youtube` wasn't really an option based on my experience creating https://issues.jenkins.io/browse/INFRA-2995. Not a problem if this isn't useful but thought I'd send it just in case.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by daniel-beck** [comment]
This is certainly wrong, `account` means https://accounts.jenkins.io (there's also `account-app`, because why not).

**Comment by oleg-nenashev** [comment]
Yes, needs a fix on the infra side/. CC @olblak @dduportal

**Comment by olblak** [comment]
I created the component "youtube", "twitter", and updated the account component description

**Comment by olblak** [comment]
Imho this PR should be closed but I don't have permission here :)

**Comment by justinharringa** [comment]
Excellent! Closing this out. Thanks all!

**Pull request closed without merging**
