### PR TITLE
Added comments/questions from svanoort

### PR DESCRIPTION
**Pull request by bitwiseman**
@oleg-nenashev 
These were the comments from @svanoort  on #151 .  I believe you can respond by editing or commenting directly on this PR (if not please tell me so we can figure out how to make that possible).   

@jglick  I believe you also had some comments/edits.  Feel free to make them here or separately.

As noted in #151, many people have take the initial submission as invitation to do a full review.  That it explicitly not how it was described in the JEP-1.  This PR is partly an experiment to explore how we can make draft submission PRs less like design reviews while still addressing the point that people want to be able to comment on JEPs. This is one way I thought we could work around the GitHub limitations on discussion/questions/suggestions outside of PRs.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
> These were the comments from @svanoort on #151 . I believe you can respond by editing or commenting directly on this PR (if not please tell me so we can figure out how to make that possible).

Looks like an attempt to replicate Google Doc.

> This is one way I thought we could work around the GitHub limitations on discussion/questions/suggestions outside of PRs.

I also have no idea how to do it better tho.
If Google Doc (or something like that) supported import/export to Asciidoc, it would be easier to do something with that, even to setup automated flow somehow

**Comment by oleg-nenashev** [comment]
I tried several external converters. Didn't work well

**Comment by bitwiseman** [comment]
Also, see #160 for an example using visible blocks instead of comments.

**Comment by bitwiseman** [comment]
@oleg-nenashev
One difference being the history is better tracked (and not deletable) in GitHub. 

And yes, I wish there were a Google doc export to asciidoc. :|

**Comment by bitwiseman** [comment]
https://asciidoctor.org/docs/migrating-from-msword/ suggests a bunch of ideas, but none are great.

**Comment by svanoort** [comment]
This is a clever approach for draft JEPs.  I think I prefer this to #160 because it doesn't clutter up the display out-of-box.  Um, I can't edit directly though -- probably because I'm not a sponsor or BDFL-delegate at the moment.

Apparently you can embed HTML into ASCIIdoc so there's room to embed scripts for expandable content blocks, i.e. "see discussion" etc.   But on the other hand, I think that is to some extent reinventing the wheel by trying to re-make Google Docs (agree with @oleg-nenashev  there). 

@bitwiseman There's a value to this technique for proposed JEPs, and/or where we want to permanently note some incidental feedback raised (also #160 where it's important it be visible when viewing the JEP).   But I still think Github PR review tooling is the best way to do the early stages.  It's just *so* much faster to iterate using that while incorporating feedback. 

@oleg-nenashev @bitwiseman My proposal would be to convert "draft" status -> "proposed" JEP status.  A proposed JEP would meet all the current criteria for a draft, but additionally should have more or less stabilized.  The sponsor would ask to go ahead into 'proposed' state if they've incorporated as much feedback as they feel able to.  JEP editors might poke them to do so when it looks like the discussion & proposal changes have settled down a bit -- that doesn't mean everyone _agrees_, of course, because there will always be compromises.

A proposed JEP would go up for discussion on the dev-list (as currently) and could still be amended based on that, but might also get accepted by the BDFL-delegate as-is if feedback is positive. 

In normal code reviews, think of a proposed JEP as equivalent to code put up for final review, the PR state preceding it as a WIP PR, and dev-list discussion as final code review votes (with the BDFL-delegate taking the role of maintainer).

**Comment by bitwiseman** [comment]
@svanoort 
"permanently note some incidental feedback raised" - That is what the Reasoning section is for. 

As to your proposal - What you are suggesting is a rather significant change.  But if you are passionate about this, you should feel free to raise this on the dev list, gather feedback, make a PR to JEP-1, drive this to completion.   Or, using the model shown in this PR (or #160), you can create a PR with your idea above in a block and people can discuss it there.

**Comment by bitwiseman** [comment]
@svanoort 
Even if you cannot make direct edits you can create PR's against my PR branch - we used that model during JEP-1.  But for simplicity, I've made you a collaborator on my fork, so you should now be able to make direct edits.

**Comment by bitwiseman** [comment]
Closing in favor of #160. We'll see how that goes.

**Pull request closed without merging**
